name = "MRIfieldmap"
uuid = "5af58b90-8a55-4daf-adb4-2008a66a38cf"
authors = ["Jeff Fessler <fessler@umich.edu> and others"]
version = "0.0.1"

[deps]
LimitedLDLFactorizations = "f5a24dde-3ab7-510b-b81b-6a72c6098d3b"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

[compat]
julia = "v1.8"
